baseURL = 'https://example.org/'
locale = 'en-us'
title = 'Robin Zen Art'


[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1
    
    [[menu.main]]
        name = "Paintings"
        url = "/paintings"
        weight = 1

    [[menu.main]]
        name = "Prints"
        url = "/prints"
        weight = 2

    [[menu.main]]
        name = "Fiber Art"
        url = "/fiber-art"
        weight = 3

    [[menu.main]]
        name = "Animations"
        url = "/animations"
        weight = 4

    [[menu.main]]
        name = "Music"
        url = "/music"
        weight = 5

    [[menu.main]]
        name = "Shop"
        url = "/shop"
        weight = 6
    